In [3]:
import torch

class TensorCalculator():

    def __init__(self): 
        return None

    def tensor_zeros(dim_x,dim_y):
        zeros = torch.zeros([dim_x,dim_y])
        return zeros

    def tensor_ones(dim_x, dim_y):
        ones = torch.ones([dim_x, dim_y])
        return ones

    def tensor_rand(dim_x, dim_y):
        random = torch.rand([dim_x,dim_y])
        return random

    def tensor_sum(dim_x, dim_y, dim_z, dim_g):
        a = torch.tensor([dim_x,dim_y])
        b = torch.tensor([dim_z,dim_g])
        sum = a + b
        return sum
    
    def tensor_mult(dim_x,dim_y,dim_z,dim_g):
        a = torch.tensor([dim_x,dim_y])
        b = torch.tensor([dim_z,dim_g])
        mult = torch.matmul(a,b)
        return mult

    def tensor_transpose(func):
        transpose = torch.transpose(func)
        return transpose

zero = TensorCalculator.tensor_zeros(5,5)
print(zero)

one = TensorCalculator.tensor_ones(5,5)
print(one)

r = TensorCalculator.tensor_rand(5,5)
print(r)

suma = TensorCalculator.tensor_sum(2,3,4,5)
print(suma)

multiplicacion = TensorCalculator.tensor_mult(1,2,3,4)
print(multiplicacion)


tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0.5924, 0.6562, 0.0759, 0.9567, 0.4992],
        [0.4575, 0.5813, 0.6594, 0.1447, 0.6384],
        [0.1141, 0.4044, 0.8623, 0.5591, 0.4366],
        [0.6773, 0.0879, 0.9836, 0.8123, 0.4943],
        [0.7890, 0.1345, 0.9381, 0.2914, 0.6539]])
tensor([6, 8])
tensor(11)
