In [1]:
import torch

ModuleNotFoundError: No module named 'torch'

In [11]:
class TensorCalculator():

    def __init__(self): 
        return None

    def tensor_zeros(dim_x,dim_y):
        zeros = torch.zeros([dim_x,dim_y])
        return zeros

    def tensor_ones(dim_x, dim_y):
        ones = torch.ones([dim_x, dim_y])
        return ones

    def tensor_rand(dim_x, dim_y):
        random = torch.rand([dim_x,dim_y])
        return random

    def tensor_sum(dim_x, dim_y, dim_z, dim_g):
        a = torch.tensor([dim_x,dim_y])
        b = torch.tensor([dim_z,dim_g])
        sum = a + b
        return sum
    
    def tensor_mult(dim_x,dim_y,dim_z,dim_g):
        a = torch.tensor([dim_x,dim_y])
        b = torch.tensor([dim_z,dim_g])
        mult = torch.matmul(a,b)
        return mult

    def tensor_transpose(func):
        transpose = torch.transpose(func)
        return transpose

zero = TensorCalculator.tensor_zeros(5,5)
print(zero)

one = TensorCalculator.tensor_ones(5,5)
print(one)

r = TensorCalculator.tensor_rand(5,5)
print(r)

suma = TensorCalculator.tensor_sum(2,3,4,5)
print(suma)

multiplicacion = TensorCalculator.tensor_mult(1,2,3,4)
print(multiplicacion)

trans = TensorCalculator.tensor_transpose(TensorCalculator.tensor_sum(2,3,4,5))
print(trans)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0.0404, 0.3614, 0.2118, 0.2502, 0.8628],
        [0.3740, 0.6891, 0.9871, 0.2516, 0.5737],
        [0.0888, 0.1346, 0.9861, 0.4536, 0.8071],
        [0.2723, 0.1077, 0.9651, 0.5978, 0.2452],
        [0.8550, 0.2299, 0.9857, 0.7600, 0.8722]])
tensor([6, 8])
tensor(11)
