In [6]:
import torch

class TensorCalculator():

    def __init__(self): 
        return None

    def tensor_zeros(dim_x,dim_y):
        zeros = torch.zeros([dim_x,dim_y])
        return zeros

    def tensor_ones(dim_x, dim_y):
        ones = torch.ones([dim_x, dim_y])
        return ones

    def tensor_rand(dim_x, dim_y):
        random = torch.rand([dim_x,dim_y])
        return random

    def tensor_sum(dim_x, dim_y, dim_z, dim_g):
        a = torch.tensor([dim_x,dim_y])
        b = torch.tensor([dim_z,dim_g])
        sum = a + b
        return sum
    
    def tensor_mult(dim_x,dim_y,dim_z,dim_g):
        a = torch.tensor([dim_x,dim_y])
        b = torch.tensor([dim_z,dim_g])
        mult = torch.matmul(a,b)
        return mult
    
    def tensor_div(dim_x,dim_y,dim_z,dim_g):
        a = torch.tensor([dim_x,dim_y])
        b = torch.tensor([dim_z,dim_g])
        mult = torch.div(a,b)
        return mult
    
    def tensor_rest(dim_x,dim_y,dim_z,dim_g):
        a = torch.tensor([dim_x,dim_y])
        b = torch.tensor([dim_z,dim_g])
        r = torch.sub(a,b)
        return r

zero = TensorCalculator.tensor_zeros(5,5)
print(zero)

one = TensorCalculator.tensor_ones(5,5)
print(one)

r = TensorCalculator.tensor_rand(5,5)
print(r)

suma = TensorCalculator.tensor_sum(2,3,4,5)
print(suma)

multiplicacion = TensorCalculator.tensor_mult(1,2,3,4)
print(multiplicacion)

division = TensorCalculator.tensor_div(1,2,3,4)
print(division)

resta = TensorCalculator.tensor_rest(1,2,3,4)
print(resta)


tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0.0044, 0.2990, 0.2298, 0.7971, 0.5141],
        [0.7710, 0.5266, 0.0788, 0.8759, 0.4284],
        [0.4598, 0.0276, 0.6828, 0.4154, 0.1583],
        [0.8410, 0.8891, 0.4527, 0.6483, 0.2127],
        [0.2406, 0.6131, 0.4794, 0.4023, 0.6387]])
tensor([6, 8])
tensor(11)
tensor([0.3333, 0.5000])
tensor([-2, -2])
